# Stuck? Check the docs at https://ryoko.klossom.io/docs #
################################
#        Ryoko  Options        #
################################
# => Global options    /
######################/
lang: en
